alias lt='ls -lhrt'
alias cl='clip.exe'
alias cls="clear"
alias cm='cd /home/steff007/mongodb/mongodb-linux-x86_64-3.6.5/bin'
alias dw='cd /mnt/c/users/jimst/Downloads'
alias eg='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fp='find `pwd` -na:
alias ga='git add '
alias gr='grep'
alias graph='git log --all --decorate --oneline --graph'
alias gs='git status '
alias hi='history'
alias ht='hi | sort -rn | cut -c 1-7 --complement | vi -'
alias i3='ipython3'
alias la='ls -A'
alias ll='ls -alF'
alias lotto='curl --silent https://www.mnlottery.com/games/lotto | html2text | sed -e 1,92d | vi -'
alias ls='ls --color=auto'