alias ip='/mnt/c/Users/jayst/AppData/Local/Programs/Python/Python310/Scripts/ipython3.exe'
alias als='alias | v -'
alias ldr='ls -td -- */ | head -n 10'
alias c="cd /mnt/c"
alias bas="cd /mnt/c/all/bash"
alias cl='clip.exe'
alias cls="clear"
alias cx="chmod +x "
alias fm='vifm'
alias fp='find `pwd` -name '
alias g='nvim'
alias gr='grep'
alias gx='ga . && gc "initial"'
alias hi='history'
alias his='hi |  cut -c 1-7 --complement | nvim -'
alias hn='hi | nvim -'
alias ht='hi | sort -rn | cut -c 1-7 --complement | nvim -'
alias hv='hi |  cut -c 1-7 --complement | nvim -'
alias i3='ipython3'
alias ifconfig.me='curl ifconfig.me && printf "\n"' 
alias la='ls -A'
alias ld='ls -la | grep "^d"'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias lt='ls -lhrt'
alias mc='cd /mnt/c'
alias md='mkdir'
alias mem='ps aux --sort -rss | nvim -'
alias mp='cd /mnt/c/projects'
alias mps='cd /mnt/c/projects'
alias nb='node --inspect-brk'
alias no='node'
alias nv='nvim'
alias p3='python3.6'
alias p7='python3'
alias pc='pwd |tr '\''\n'\'' '\'' '\'' | clip.exe'
alias pow='powershell.exe'
alias py="python"
alias ran='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'
alias se='history | grep '
alias ssp="python3 -m http.server"
alias u='cd ..'
alias v='nvim '
alias vi='nvim '
alias vn='nvim -p ~/dotfiles/notes/n.txt ~/dotfiles/notes/pw.txt'
alias y3='youtube-dl -x --audio-format mp3 '
alias y4='youtube-dl -f 18 '
alias duh='du -h --max-depth=1'
alias lf='exa  -a --group-directories-first'
# Aliases
alias g='git'
compdef g=git
alias gst='git status'
compdef _git gst=git-status
alias gl='git pull'
compdef _git gl=git-pull
alias gup='git fetch && git rebase'
compdef _git gup=git-fetch
alias gp='git push'
compdef _git gp=git-push
gdv() { git diff -w "$@" | view - }
compdef _git gdv=git-diff
alias gc='git commit -v'
compdef _git gc=git-commit
alias gca='git commit -v -a'
compdef _git gca=git-commit
alias gco='git checkout'
compdef _git gco=git-checkout
alias gcm='git checkout master'
alias gb='git branch'
compdef _git gb=git-branch
alias gba='git branch -a'
compdef _git gba=git-branch
alias gcount='git shortlog -sn'
compdef gcount=git
alias gcp='git cherry-pick'
compdef _git gcp=git-cherry-pick
alias glg='git log --stat --max-count=5'
compdef _git glg=git-log
alias glgg='git log --graph --max-count=5'
compdef _git glgg=git-log
alias gss='git status -s'
compdef _git gss=git-status
alias ga='git add'
compdef _git ga=git-add
alias gm='git merge'
compdef _git gm=git-merge
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias fdh='fd -help'
alias rgh='rg -help'
